# Generated by Django 4.1.3 on 2022-11-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0002_funcionario_dono"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="funcionario",
            name="dono",
        ),
        migrations.AddField(
            model_name="user",
            name="dono",
            field=models.BooleanField(default=False),
        ),
    ]
